export type Locale = 'en' | 'zh';

export const localeLabels: Record<Locale, string> = {
  en: 'EN',
  zh: '中文',
};

export const dictionaries = {
  en: {
    navigation: { dashboard: 'Dashboard', invoices: 'Invoices', customers: 'Customers', home: 'Home', language: 'Language' },
        invoice: { invoice: 'Invoice', invoiceNumber: 'Invoice number', issued: 'Issued', from: 'From', billTo: 'Bill to', customer: 'Customer', description: 'Description', quantity: 'Quantity', unitPrice: 'Unit Price', subtotal: 'Subtotal', discount: 'Discount', total: 'Total Amount', totalDue: 'Total due', professionalBilling: 'Professional billing statement', billingDepartment: 'Billing Department', thankYou: 'Thank you for your business.', records: 'Please retain this invoice for your records.', backToInvoices: 'Back to invoices', loading: 'Loading invoice...', notFound: 'Invoice not found.', newInvoice: 'New invoice', createInvoice: 'Create invoice', recent: 'Recent invoices', viewAll: 'View all', totalUnpaid: 'Total unpaid', paidInvoices: 'Paid invoices', outstandingBalance: 'Outstanding invoice balance', completedPayments: 'Completed payments', quickAction: 'Quick action', manageCustomers: 'Manage customers', latestActivity: 'Your latest billing activity', noInvoices: 'No invoices yet. Create your first invoice to get started.', workspace: 'Workspace / Billing', search: 'Search invoice number or customer', allStatuses: 'All statuses', noMatch: 'No invoices match your search.', date: 'Date', totalShort: 'Total', loadingInvoices: 'Loading invoices...', newTitle: 'New invoice', editTitle: 'Edit invoice', prepare: 'Prepare a clear, accurate invoice in a few quick steps.', addCustomer: 'Add customer', browseSpecifications: 'Browse common specifications', manageCustomer: 'Manage customers', selectCustomer: 'Select a customer', items: 'Items', addItem: 'Add item', customItem: 'Custom item', productSpecification: 'Product / specification', itemDescription: 'Description', qty: 'Qty', unitPriceShort: 'Unit price', saveInvoice: 'Save invoice', savingInvoice: 'Saving...', lessDiscount: 'Less / discount', preview: 'Preview Invoice', close: 'Close', savePrint: 'Save & Print', delete: 'Delete', void: 'Void', confirmVoid: 'Void invoice?', confirmVoidDescription: 'This invoice will be marked as VOID and excluded from total amounts.', voiding: 'Voiding...', edit: 'Edit' },
    customer: { directory: 'Directory', title: 'Customers', description: 'Keep customer details ready for your next invoice.', create: 'Create invoice', add: 'Add customer', addDescription: 'Name is required. Company and phone help with follow-up.', name: 'Name', company: 'Company', contactPerson: 'Contact person', email: 'Email', phone: 'Phone', address: 'Address', registrationNo: 'Registration No', sstNo: 'SST No', list: 'Customer list', saved: 'saved customers', loading: 'Loading customers...', empty: 'No customers yet. Add your first customer.', unnamed: 'Unnamed customer', noCompany: 'No company listed', noPhone: 'No phone listed', adding: 'Adding...', added: 'Customer added successfully.', edit: 'Edit', update: 'Update customer', delete: 'Delete', cancel: 'Cancel', confirmDelete: 'Delete customer?', confirmDeleteDescription: 'This action cannot be undone.', deleting: 'Deleting...', updated: 'Customer updated successfully.', deleted: 'Customer deleted successfully.', invoiceBlock: 'This customer has invoice records and cannot be deleted directly.' },
    status: { paid: 'Paid', unpaid: 'Unpaid', void: 'Void', paidUpper: 'PAID', unpaidUpper: 'UNPAID', voidUpper: 'VOID' },
    actions: { markPaid: 'Mark as Paid', markUnpaid: 'Mark as Unpaid', saving: 'Saving...', print: 'Print / Export PDF', shareWhatsApp: 'Share via WhatsApp', duplicate: 'Duplicate', toggleMenu: 'Toggle navigation' },
  },
  zh: {
    navigation: { dashboard: '仪表盘', invoices: '发票', customers: '客户', home: '首页', language: '语言' },
        invoice: { invoice: '发票', invoiceNumber: '发票编号', issued: '开具日期', from: '开票方', billTo: '客户信息', customer: '客户', description: '描述', quantity: '数量', unitPrice: '单价', subtotal: '小计', discount: '折扣', total: '总金额', totalDue: '应付总额', professionalBilling: '专业账单明细', billingDepartment: '账单部门', thankYou: '感谢您的惠顾。', records: '请妥善保存此发票。', backToInvoices: '返回发票列表', loading: '正在加载发票...', notFound: '未找到发票。', newInvoice: '新建发票', createInvoice: '创建发票', recent: '最近发票', viewAll: '查看全部', totalUnpaid: '未付款总额', paidInvoices: '已付款发票', outstandingBalance: '待收发票金额', completedPayments: '已完成付款', quickAction: '快捷操作', manageCustomers: '管理客户', latestActivity: '最近账单动态', noInvoices: '暂无发票。创建第一张发票开始使用。', workspace: '工作台 / 账单', search: '搜索发票编号或客户', allStatuses: '全部状态', noMatch: '没有匹配的发票。', date: '日期', totalShort: '总额', loadingInvoices: '正在加载发票...', newTitle: '新建发票', editTitle: '编辑发票', prepare: '快速创建一张清晰准确的发票。', addCustomer: '添加客户', browseSpecifications: '查看常用规格', manageCustomer: '管理客户', selectCustomer: '选择客户', items: '明细', addItem: '添加明细', customItem: '自定义项目', productSpecification: '产品 / 规格', itemDescription: '描述', qty: '数量', unitPriceShort: '单价', saveInvoice: '保存发票', savingInvoice: '保存中...', lessDiscount: '折扣', preview: '预览发票', close: '关闭', savePrint: '保存并打印', delete: '删除', void: '作废', confirmVoid: '作废发票？', confirmVoidDescription: '该发票将被标记为作废 (VOID)，且金额不计入统计。', voiding: '作废中...', edit: '编辑' },
    customer: { directory: '客户目录', title: '客户', description: '维护客户信息，快速用于下一张发票。', create: '创建发票', add: '添加客户', addDescription: '姓名为必填项，公司和电话便于后续联系。', name: '姓名', company: '公司', contactPerson: '联系人', email: '邮箱', phone: '电话', address: '地址', registrationNo: '注册编号', sstNo: 'SST 编号', list: '客户列表', saved: '位已保存客户', loading: '正在加载客户...', empty: '暂无客户，请添加第一位客户。', unnamed: '未命名客户', noCompany: '未填写公司', noPhone: '未填写电话', adding: '添加中...', added: '客户添加成功。', edit: '编辑', update: '更新客户', delete: '删除', cancel: '取消', confirmDelete: '删除客户？', confirmDeleteDescription: '此操作无法撤销。', deleting: '删除中...', updated: '客户更新成功。', deleted: '客户删除成功。', invoiceBlock: '该客户下已有发票记录，无法直接删除。' },
    status: { paid: '已付款', unpaid: '未付款', void: '已作废', paidUpper: '已付款', unpaidUpper: '未付款', voidUpper: '已作废' },
    actions: { markPaid: '标记为已付款', markUnpaid: '标记为未付款', saving: '保存中...', print: '打印 / 导出 PDF', shareWhatsApp: '通过 WhatsApp 分享', duplicate: '复制发票', toggleMenu: '切换导航菜单' },
  },
} as const;

export type Translation = typeof dictionaries.en | typeof dictionaries.zh;
